### ISSUE TITLE
dashboard pod doesn't deploy properly

### ISSUE THREAD

**Issue by adezxc** [sorry-cypress/charts#78] opened 2021-11-26 16:06 UTC
## Summary

Sorry cypress dashboard doesn't deploy dashboard properly, getting Error: Unexpected token < in JSON at position 0

## How to reproduce

`helm install sorry-cypress sorry-cypress/sorry-cypress`

`kubectl port-forward svc/sorry-cypress-dashboard 8080`
`kubectl port-forward svc/sorry-cypress-director 1234`

Then I just get `Error: Unexpected token < in JSON at position 0` in localhost:8080

## Environment

- sorry-cypress version: `1.1.1`
- cypress version: `9.1.0`
- helm chart version: latest, not sure how to fetch that

**Comment by tico24** [comment] 2021-11-29 07:03
Hi there. I can assure you that it does deploy out of the box. The CI wouldn't let us release the helm chart until a deployment test has completed on all cncf-supported versions of k8s (Currently 1.20+): https://github.com/sorry-cypress/charts/actions/runs/1490150757

Can you provide information on your kubernetes version please?

**Comment by abstrakct** [comment] 2021-11-29 11:40
Hi, I'm no the OP, but I'm having the same problem. Deployed on a microk8s cluster.


kubectl version: 
`Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.4-3+adc4115d990346", GitCommit:"adc4115d990346b87714cc4f033d225711bf744d", GitTreeState:"clean", BuildDate:"2021-11-17T22:03:17Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
`

The pods deploy/run, but something is wrong.

Screenshot:
![image](https://user-images.githubusercontent.com/182898/143859825-c3c1784f-32c5-4822-af92-c0fd1d63c644.png)

Javascript console:
`DevTools failed to load source map: Could not parse content for http://dashboard.chart-example.local/normalize.min.css.map: Unexpected token < in JSON at position 0`
and
`POST http://dashboard.chart-example.local/graphql 405 (Not Allowed)`

wget http://dashboard.chart-example.local/normalize.min.css.map returns this:
`<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="description" content="sorry-cypress dashboard"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/><link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/><link rel="manifest" href="/site.webmanifest"/><link rel="mask-icon" href="/safari-pinned-tab.svg" color="#fff"/><meta name="msapplication-TileColor" content="#fff"/><meta name="theme-color" content="#ffffff"/><title>Sorry-cypress dashboard</title><link href="/normalize.min.css" rel="stylesheet"/><link href="/fonts.css" rel="stylesheet"/><script>window.__sorryCypressEnvironment = { GRAPHQL_CLIENT_CREDENTIALS: "", GRAPHQL_SCHEMA_URL: "", CI_URL: "" };</script></head><body><div id="app"></div><script src="/index.mjs?7c414d4a50b2d7e877cb"></script></body></html>`

I'm fairly new to kubernetes, but I'm guessing this might be related to settings in the values.yaml file? GraphQL credentials? I get this error even when I use the default values. The documentation for all the configuration options is a bit hard to understand for me - for example, are all of them optional, or are some mandatory? Should everything (in theory) work with the defaults? 

Thanks for any help.

**Comment by tico24** [comment] 2021-11-29 11:42
Ah, well that's a sorry cypress error. Not a helm chart error. Are you also running sorry-cypress 1.1.1?

**Comment by abstrakct** [comment] 2021-11-29 11:52
Ok, thanks! Yes, v1.1.1

**Comment by tico24** [comment] 2021-11-29 12:22
Having a copy of your values.yml will indeed be helpful. Or, if you don't want to do that, output a helm template to a yaml file, and maybe that'll help you pinpoint the root cause?

To answer your question though, no, the default values won't be enough for the dashboard to work. Looking again at that error in the UI, the problem here is that you have not set Dashboard environment variables: https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/values.yaml#L107

The POST error and the javascript error above is because you haven't set this URL: https://github.com/sorry-cypress/charts/blob/main/charts/sorry-cypress/values.yaml#L126

**Comment by abstrakct** [comment] 2021-11-29 13:34
Right, thanks a lot! And it looks like these urls must accessible from the outside, not just within the cluster.

I think I'm on the right track now.

**Comment by tico24** [comment] 2021-11-29 13:37
Yup. Your browser needs to see them. I get that it's confusing.

You might find looking at the docker-compose examples in the main repo will help you with the setup.

**Comment by ILyaMotkov** [comment] 2021-11-30 18:52
Hi, @tico24 i have same values.yaml, but i get an error Error: Failed to fetch, can you help with full example values for running director, API, Dashboard?
`api:
  image:
    repository: agoldis/sorry-cypress-api
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    # tag: "latest"

  # If you have no need for the API service, you can set this to false to exclude it
  enabled: true

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # You can define any init container(s) here.
  # This example checks that mongodb is running before allowing the api pod to start.
  # If you wish to do this, you will need to modify your RBAC settings (not included in this Helm chart)
  initContainers: []
  # - name: waitformongo
  #   image: groundnuty/k8s-wait-for
  #   args:
  #     - "pod"
  #     - "-lapp.kubernetes.io/name=mongodb"

  service:
    port: 4000

  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 2
    failureThreshold: 5

  # Set annotations for pods
  podAnnotations: {}

  # Additional pod labels
  podLabels: {}

  ingress:
    ingressClassName: nginx
    labels: {}
    annotations:
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-type: basic
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: api.192.168.157.128.nip.io
        path: /
    tls:
      - secretName: api-sorry-cypress-tls
        hosts:
          - api.192.168.157.128.nip.io

dashboard:
  image:
    repository: agoldis/sorry-cypress-dashboard
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    # tag: "latest"

  # If you have no need for the Dashboard service, you can set this to false to exclude it.
  enabled: true

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  initContainers: []

  # https://sorry-cypress.dev/dashboard#configuration
  environmentVariables:
    graphQlClientCredentials: ""
    graphQlSchemaUrl: "sorry-cypress-api:4000"
    ciUrl: ""

  service:
    port: 8080

  # Set annotations for pods
  podAnnotations: {}

  # Additional pod labels
  podLabels: {}

  ingress:
    enabled: true
    ingressClassName: nginx
    labels: {}
    annotations: {}
#      nginx.ingress.kubernetes.io/auth-realm: Authentication Required
#      nginx.ingress.kubernetes.io/auth-secret: basic-auth
#      nginx.ingress.kubernetes.io/auth-type: basic
#      kubernetes.io/tls-acme: "true"
    hosts:
      - host: dashboard.192.168.157.128.nip.io
        path: /
    tls:
      - secretName: dashboard-sorry-cypress-tls
        hosts:
          - dashboard.192.168.157.128.nip.io

director:
  serviceAccountName: "default"
  image:
    repository: agoldis/sorry-cypress-director
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    # tag: "latest"

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # You can define any init container(s) here.
  # This example checks that mongodb is running before allowing the api pod to start.
  # If you wish to do this, you will need to modify your RBAC settings (not included in this Helm chart)
  initContainers: []
  # - name: waitformongo
  #   image: groundnuty/k8s-wait-for
  #   args:
  #     - "pod"
  #     - "-lapp.kubernetes.io/name=mongodb"

  environmentVariables:
    # The "Run URL" in the Cypress client
    dashboardUrl: ""

    # In memory, or Mongo.
    # Valid options are:
    # "../execution/in-memory"
    # "../execution/mongo/driver"
    executionDriver: "../execution/in-memory"

    # Dummy or S3
    # Valid options are:
    # "../screenshots/dummy.driver"
    # "../screenshots/s3.driver"
    screenshotsDriver: "../screenshots/dummy.driver"

    # https://docs.sorry-cypress.dev/configuration/director-configuration
    allowedKeys: ""

    # Test runs timeouts
    inactivityTimeoutSeconds: ""

  # Set annotations for pods
  podAnnotations: {}

  # Additional pod labels
  podLabels: {}

  service:
    port: 1234

  ingress:
    enabled: true
    ingressClassName: nginx
    labels: {}
    annotations:
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-type: basic
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: director.192.168.157.128.nip.io
        path: /
    tls:
      - secretName: director-sorry-cypress-tls
        hosts:
          - director.192.168.157.128.nip.io

mongodb:
  replicaCount: 1
  # You need to ensure that director.environmentVariables.executionDriver is set to "../execution/mongo/driver" if you want the director to use mongodb.
  mongoConnectionString: ""

  # Set this to "true" if you wish to use your own external mongodb.
  external_db:
    enabled: false
    mongoServer: ""

  # Set this to "true" if you want this chart to deploy mongodb for you.
  internal_db:
    enabled: true

  mongoDatabase: "sorry-cypress"

  # If enabled, you can use any values from the mongodb helm chart: https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
  # Below are the bare minimim to get you started.
  architecture: replicaset
  auth:
    enabled: false

  resources:
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 25m
      memory: 90Mi

  persistence:
    enabled: false
    size: 1Gi

  externalAccess:
    enabled: true
    service:
      type: ClusterIP

s3:
  bucketName: sorry-cypress
  region: us-east-1
  accessKeyId: ""
  secretAccessKey: ""
  acl: "public-read"
  readUrlPrefix: ""
#
#  ingress:
#    # When enabling ingress, an ExternalName service will be also created to expose the bucket.
#    enabled: false
#    ingressClassName: nginx
#    labels: {}
#    annotations: {}
#      # kubernetes.io/tls-acme: "true"
#      # nginx.ingress.kubernetes.io/upstream-vhost: <bucket>.s3-website-<region>.amazonaws.com
#      # nginx.ingress.kubernetes.io/enable-cors: "true"
#      # nginx.ingress.kubernetes.io/cors-allow-origin: "*"
#    # nginx.ingress.kubernetes.io/cors-allow-methods: "POST, GET, PUT, DELETE, HEAD"
#    hosts:
#      - host: static.192.168.157.128.nip.io
#        path: /
#    tls: []
#    #  - secretName: chart-example-tls
#    #    hosts:
#    #      - chart-example.local

minio:
  enabled: true
  ingress:
    enabled: true
    annotations:
#      nginx.ingress.kubernetes.io/auth-realm: Authentication Required
#      nginx.ingress.kubernetes.io/auth-secret: basic-auth
#      nginx.ingress.kubernetes.io/auth-type: basic
      kubernetes.io/tls-acme: "true"
    hosts:
      - minio.192.168.157.128.nip.io
    path: /
    tls:
      - secretName: minio-sorry-cypress-tls
        hosts:
          - minio.192.168.157.128.nip.io

  # If enabled, you can include any values from the minio helm chart: https://github.com/minio/charts/blob/master/minio/values.yaml
  # Below are the bare minimim to get you started.

  endpoint: sorry-cypress-minio
  url: http://sorry-cypress-minio

  defaultBucket:
    enabled: true
    name: sorry-cypress

  persistence:
    size: 5Gi

#kubectl create secret generic basic-auth --from-file=auth -n sorry-cypress`

**Comment by tico24** [comment] 2021-12-24 09:05
I am going to close this as no further information has been provided by @adezxc

**Closed by tico24** 2021-12-24 09:05 UTC
